### ISSUE TITLE
Z DIR_PIN Direction

### ISSUE THREAD

**Issue by zervin** [etet100/klipper-flashforge-creator-pro#2]
[klippy.log](https://github.com/etet100/klipper-flashforge-creator-pro/files/4033046/klippy.log)

I needed to reverse the Z pin direction. Homing was heading away from the pin. Otherwise, initial basic tests are looking great, preparing for some test prints.

dir_pin: !PK0

**Comment by etet100** [comment]
Sorry about that. I forgot to mention that my z axis is heavily modified (https://www.thingiverse.com/thing:3820186). I will update config file.

**Comment by zervin** [comment]
No worries. I made a few other changes..before my board locked up last night during a print. I am going to see if I can recover it tonight. It was already showing signs of failure and lots of disconnects and print stalls. I think the Z axis steps were wrong as well. I can attach my current cfg this evening.

Only the left arrow on the display seemed to work as well.

**Comment by etet100** [comment]
If i remember correctly default steps per mm for z axis is 400, so the step_distance is .0025

All buttons should work (except right arrow which is not supported by klipper).

**Comment by zervin** [comment]
Correct, but you have 0.000666666666 as the step distance in the config file sample.
